# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    environment:
      POSTGRES_DB: methane_leaks_db
      POSTGRES_USER: methane_user
      POSTGRES_PASSWORD: methane_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: